version: 2.1
jobs:
  build:
    docker:
      #以降のコマンドは一つ目のイメージをベースに実行
      - image: circleci/php:7.3-node-browsers
      - image: circleci/postgres:11.6-alpine
        environment:
          #postgresの設定
          POSTGRES_DB: larasns
          POSTGRES_USER: default
          POSTGRES_PASSWORD: secret
    #laravel のdatabase.phpに適用
    environment:
      #laravel の環境変数を設定、build全体に適用
      #APP_ENV はテスト、本番のような環境設定
      APP_ENV: testing
      #laravel-ci/phpunit.xmlのDB_CONNECTIONをsqlite
      #からpgsql に設定
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      #circleci/postgres:11.6-alpine はDockerfile
      #が EXPOSE 5432
      #localhost:5432 でpostgresにつながる
      #docker-compose.ymlの5432:5432はPCとコンテナを繋ぐ設定である
      #コンテナ同士であればDB_portと接続先のコンテナのポートが同じであれば良い
      #こうすれば、localhost:5432で接続できる。

      DB_PORT: 5432
      DB_DATABASE: larasns
      DB_USERNAME: default
      DB_PASSWORD: secret
    steps:
      - checkout
      - run: sudo composer self-update --1
      - restore_cache:
          #composer.lock のハッシュ値を　keyに含め、composer-v1 として保存(ハッシュ値とcomposer-v1を紐付け)。
          #保存するディレクトリはvendor。
          #composer.lock が変化すれば保存し直す。
          #ハッシュ値を見て同じだったら、このvendor 使えるよ〜みたいな感じ
          key: composer-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run dev
      - run:
          name: get ready for postgres
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_pgsql
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: php test
          command: vendor/bin/phpunit
  deploy:
    docker:
      - image: circleci/php:7.3-node-browsers
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout

      - run: sudo composer self-update --1
      - restore_cache:
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
      - run: composer install -n --no-dev --prefer-dist
      - save_cache:
          key: composer-no-dev-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run prod
      - run:
          name: archive artifacts
          command: zip -ryq laravel-ci.zip .
      - aws-cli/install
      - run:
          name: upload artifacts to s3
          command: aws s3 cp laravel-ci.zip s3://${AWS_S3_BUCKET_NAME}
      - run:
          name: deploy to prod
          command: |
            aws deploy create-deployment \
            --application-name laravel-ci \
            --deployment-group-name laravel-ci \
            --s3-location bucket=${AWS_S3_BUCKET_NAME},key=laravel-ci.zip,bundleType=zip
  deploy_tmp:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: deploy to prod
          command: |
            echo -e "Host git-codecommit.*.amazonaws.com\n   User ${AWS_SSH_KEY_ID}\n   StrictHostKeyChecking no" > ${HOME}/.ssh/config
            git push ssh://git-codecommit.ap-northeast-1.amazonaws.com/v1/repos/laravel-ci
orbs:
  aws-cli: circleci/aws-cli@1.0.0

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy_tmp:
          requires:
            - build
          filters:
            branches:
              only:
                - master
